"""
rules package for Daylite Person Quality engine.
Aggregates all 37 quality rules across 6 dimensions.
"""

from app.modules.person.quality.models import QualityRule
from app.modules.person.quality.rules.addresses import (
    ADDR_CITY_WITHOUT_STATE_WHERE_SQL,
    ADDR_DUPLICATE_SAME_PERSON_WHERE_SQL,
    ADDR_INVALID_PIN_FORMAT_WHERE_SQL,
    ADDR_MISSING_GEOCODES_WHERE_SQL,
    ADDR_MISSING_POSTAL_CODE_WHERE_SQL,
    ADDR_STREET_WITHOUT_CITY_WHERE_SQL,
    ADDRESS_RULES,
)
from app.modules.person.quality.rules.audit import (
    AUDIT_DEL_BEFORE_ENT_WHERE_SQL,
    AUDIT_RULES,
    DELETED_MISSING_DEL_DATE_WHERE_SQL,
    SYNC_ZIMBRA_MISSING_ID_WHERE_SQL,
)
from app.modules.person.quality.rules.contacts import (
    CONTACT_RULES,
    DUPLICATE_EMAIL_CROSS_WHERE_SQL,
    DUPLICATE_EMAIL_SAME_WHERE_SQL,
    DUPLICATE_PHONE_CROSS_WHERE_SQL,
    DUPLICATE_PHONE_SAME_WHERE_SQL,
    INVALID_EMAIL_WHERE_SQL,
    INVALID_PHONE_WHERE_SQL,
    INVALID_URL_WHERE_SQL,
    MULTIPLE_PRIMARY_WHERE_SQL,
    PRIMARY_INACTIVE_WHERE_SQL,
    UNVERIFIED_CONTACT_WHERE_SQL,
)
from app.modules.person.quality.rules.governance import (
    BLACKLIST_MISSING_DETAILS_WHERE_SQL,
    BLACKLIST_UNAPPROVED_WHERE_SQL,
    COMPANY_DUPLICATE_LINKS_WHERE_SQL,
    COMPANY_MISSING_ROLE_WHERE_SQL,
    COMPANY_ORPHAN_LINKS_WHERE_SQL,
    DUPLICATE_EXTRA_FIELDS_WHERE_SQL,
    EXTRA_FIELD_DUPLICATE_ENTRIES_WHERE_SQL,
    EXTRA_FIELD_ORPHAN_ID_WHERE_SQL,
    GOVERNANCE_RULES,
)
from app.modules.person.quality.rules.lifecycle import (
    ACTIVE_EMP_MISSING_TITLE_WHERE_SQL,
    INACTIVE_WITH_EMPID_WHERE_SQL,
    LIFECYCLE_RULES,
    STALE_TEMP_PERSONS_WHERE_SQL,
    STATUS_ACTIVE_AND_DELETED_WHERE_SQL,
)
from app.modules.person.quality.rules.profile import (
    PERSON_ANNIVERSARY_BEFORE_BIRTH_WHERE_SQL,
    PERSON_BIRTH_DATE_ANCIENT_WHERE_SQL,
    PERSON_INVALID_BIRTH_DATE_WHERE_SQL,
    PERSON_MISSING_LASTNAME_ONLY_WHERE_SQL,
    PERSON_SUSPICIOUS_DUMMY_NAMES_WHERE_SQL,
    PROFILE_RULES,
)

ALL_RULES: list[QualityRule] = [
    *CONTACT_RULES,
    *ADDRESS_RULES,
    *PROFILE_RULES,
    *LIFECYCLE_RULES,
    *GOVERNANCE_RULES,
    *AUDIT_RULES,
]

__all__ = [
    "ACTIVE_EMP_MISSING_TITLE_WHERE_SQL",
    "ADDRESS_RULES",
    "ADDR_CITY_WITHOUT_STATE_WHERE_SQL",
    "ADDR_DUPLICATE_SAME_PERSON_WHERE_SQL",
    "ADDR_INVALID_PIN_FORMAT_WHERE_SQL",
    "ADDR_MISSING_GEOCODES_WHERE_SQL",
    "ADDR_MISSING_POSTAL_CODE_WHERE_SQL",
    "ADDR_STREET_WITHOUT_CITY_WHERE_SQL",
    "ALL_RULES",
    "AUDIT_DEL_BEFORE_ENT_WHERE_SQL",
    "AUDIT_RULES",
    "BLACKLIST_MISSING_DETAILS_WHERE_SQL",
    "BLACKLIST_UNAPPROVED_WHERE_SQL",
    "COMPANY_DUPLICATE_LINKS_WHERE_SQL",
    "COMPANY_MISSING_ROLE_WHERE_SQL",
    "COMPANY_ORPHAN_LINKS_WHERE_SQL",
    "CONTACT_RULES",
    "DELETED_MISSING_DEL_DATE_WHERE_SQL",
    "DUPLICATE_EMAIL_CROSS_WHERE_SQL",
    "DUPLICATE_EMAIL_SAME_WHERE_SQL",
    "DUPLICATE_EXTRA_FIELDS_WHERE_SQL",
    "DUPLICATE_PHONE_CROSS_WHERE_SQL",
    "DUPLICATE_PHONE_SAME_WHERE_SQL",
    "EXTRA_FIELD_DUPLICATE_ENTRIES_WHERE_SQL",
    "EXTRA_FIELD_ORPHAN_ID_WHERE_SQL",
    "GOVERNANCE_RULES",
    "INACTIVE_WITH_EMPID_WHERE_SQL",
    "INVALID_EMAIL_WHERE_SQL",
    "INVALID_PHONE_WHERE_SQL",
    "INVALID_URL_WHERE_SQL",
    "LIFECYCLE_RULES",
    "MULTIPLE_PRIMARY_WHERE_SQL",
    "PERSON_ANNIVERSARY_BEFORE_BIRTH_WHERE_SQL",
    "PERSON_BIRTH_DATE_ANCIENT_WHERE_SQL",
    "PERSON_INVALID_BIRTH_DATE_WHERE_SQL",
    "PERSON_MISSING_LASTNAME_ONLY_WHERE_SQL",
    "PERSON_SUSPICIOUS_DUMMY_NAMES_WHERE_SQL",
    "PRIMARY_INACTIVE_WHERE_SQL",
    "PROFILE_RULES",
    "STALE_TEMP_PERSONS_WHERE_SQL",
    "STATUS_ACTIVE_AND_DELETED_WHERE_SQL",
    "SYNC_ZIMBRA_MISSING_ID_WHERE_SQL",
    "UNVERIFIED_CONTACT_WHERE_SQL",
]
