from app.modules.models import (
    ModuleDefinition,
    ModuleRelationshipDefinition,
    ModuleTableDefinition,
    ModuleTableRole,
)

AttendanceModuleDefinition = ModuleDefinition(
    code="ATTENDANCE",
    name="Attendance & Leave Analysis",
    description="Automated discovery, daily punch logs, shift rosters, overtime tracking, leave applications, monthly leave balances, and 14 data quality rules.",
    root_schema="dbo",
    root_table="PayAttendance",
    root_key="AttID",
    tables=[
        ModuleTableDefinition(
            schema="dbo",
            table="PayAttendance",
            role=ModuleTableRole.ROOT,
            required=True,
            key_columns=["AttID"],
            important_columns=[
                "AttID",
                "AttEmpID",
                "AttDate",
                "AttSalType",
                "AttActInTime",
                "AttActOutTime",
                "AttOffInTime",
                "AttOffOutTime",
                "AttShiftID",
                "AttActOTMins",
                "AttLateComeMins",
                "AttEarlyGoneMins",
            ],
            description="Primary daily processed attendance records containing punch-in/out, shift IDs, overtime, late arrival, and leave labels.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeAttendance",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["AttendanceID"],
            important_columns=[
                "AttendanceID",
                "EmpID",
                "AttDate",
                "AttInTime",
                "AttOutTime",
                "AttStatus",
            ],
            description="Daily employee attendance punches and attendance status logs.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="AttendaceSyncMst",
            role=ModuleTableRole.LOG,
            required=False,
            key_columns=["SyncID"],
            important_columns=["SyncID", "EmpID", "Entdt"],
            description="Biometric device punch synchronization logs.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="PayShiftMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["ShiftID"],
            important_columns=[
                "ShiftID",
                "ShiftCode",
                "ShiftDescription",
                "FromTime",
                "ToTime",
                "ActShiftMins",
                "IsActive",
            ],
            description="Shift master defining shift timings, working minutes, grace periods, and overtime parameters.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="LeaveTypeMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["LeaveTypeID"],
            important_columns=[
                "LeaveTypeID",
                "LeaveTypeDesc",
                "LeaveTypeShortName",
                "LeaveWeighted",
                "LeaveTypeIsActive",
                "LeaveTypeIsDeleted",
            ],
            description="Leave type master catalog defining PL, CL, SL, CO, ML, LWP, weighted values, and active statuses.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="LeaveRequest",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["LeaveRequestID"],
            important_columns=[
                "LeaveRequestID",
                "LeaveRequestByEmpID",
                "LeaveRequestFromDate",
                "LeaveRequestToDate",
                "LeaveTypeID",
                "LeaveDays",
                "LeaveStatusID",
                "LeaveCancel",
                "LeaveRequestIsDeleted",
            ],
            description="Leave application headers submitted by employees.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="PayMonthlyLeaveBalance",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["BalID"],
            important_columns=[
                "BalID",
                "YearMonth",
                "EmpID",
                "TotalPresent",
                "TotalAbsent",
                "OpPL",
                "EarnedPL",
                "AvailedPL",
            ],
            description="Monthly employee leave ledger tracking opening, earned, availed, encashed, and net closing balances.",
        ),
    ],
    relationships=[
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.PayAttendance",
            parent_key="EmpID",
            child_key="AttEmpID",
            relationship_type="ONE_TO_MANY",
            confidence_score=1.0,
            description="Employee master to daily attendance logs",
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.PayShiftMst",
            child_table="dbo.PayAttendance",
            parent_key="ShiftID",
            child_key="AttShiftID",
            relationship_type="ONE_TO_MANY",
            confidence_score=1.0,
            description="Shift master to daily attendance logs",
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.LeaveRequest",
            parent_key="EmpID",
            child_key="LeaveRequestByEmpID",
            relationship_type="ONE_TO_MANY",
            confidence_score=1.0,
            description="Employee master to leave applications",
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.LeaveTypeMst",
            child_table="dbo.LeaveRequest",
            parent_key="LeaveTypeID",
            child_key="LeaveTypeID",
            relationship_type="ONE_TO_MANY",
            confidence_score=1.0,
            description="Leave type master to leave applications",
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.PayMonthlyLeaveBalance",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            confidence_score=1.0,
            description="Employee master to monthly leave balance ledger",
        ),
    ],
)
