from app.modules.models import (
    ModuleDefinition,
    ModuleRelationshipDefinition,
    ModuleTableDefinition,
    ModuleTableRole,
)

EmployeeModuleDefinition = ModuleDefinition(
    code="EMPLOYEE",
    name="Employee & Workforce",
    description="Comprehensive intelligence for employee master records, position history, organizational departments, designations, locations, multi-tiered reporting hierarchy, authentication accounts, attendance, leave, and payroll.",
    root_schema="dbo",
    root_table="EmployeeMst",
    root_key="EmpID",
    tables=[
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeMst",
            role=ModuleTableRole.ROOT,
            required=True,
            key_columns=["EmpID"],
            important_columns=[
                "EmpID",
                "EmpCode",
                "EmpTitle",
                "EmpFirstName",
                "EmpMiddleName",
                "EmpLastName",
                "CompID",
                "EmpTypeID",
                "EmpBirthDate",
                "EmpGender",
                "EmpEmailIDCompany",
                "EmpEmailIDPersonal",
                "EmpPhone1",
                "EmpPANNo",
                "AadharCardNo",
                "EmpJoinDate",
                "EmpResignDate",
                "EmpIsActive",
                "EmpIsDeleted",
            ],
            description="Core master entity for physical employees and workforce roster.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeOfficialDet",
            role=ModuleTableRole.DETAIL,
            required=True,
            key_columns=["EmpOfficeDetID", "EmpID"],
            important_columns=[
                "EmpOfficeDetID",
                "EmpID",
                "LocID",
                "DeptID",
                "DesigID",
                "EmpGradeID",
                "JoiningDate",
                "ResignDate",
                "ApplicableFrDate",
                "ProbationPeriodDays",
                "NoticePeriodDays",
                "EmpOfficeDetIsActive",
                "EmpOfficeDetIsDeleted",
            ],
            description="Position history, official department, designation, location, and grade assignments.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeReportingDet",
            role=ModuleTableRole.DETAIL,
            required=True,
            key_columns=["EmpReportingDetID", "EmpID"],
            important_columns=[
                "EmpReportingDetID",
                "EmpID",
                "ReportingEmpID",
                "CompID",
                "DesigID",
                "ReportingCompID",
                "ReportingDesigID",
                "ReportingDetIsActive",
                "ReportingDetIsDeleted",
            ],
            description="Direct reporting lines linking employees to functional and administrative managers.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="SecurityUserMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["UserID"],
            important_columns=[
                "UserID",
                "UserEmpID",
                "UserName",
                "UserEmail",
                "UserADID",
                "RoleID",
                "UserIsActive",
                "UserIsDeleted",
            ],
            description="System login authentication accounts linked to employees via UserEmpID.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="OrgCompanyMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["CompID"],
            important_columns=["CompID", "CompCode", "CompName", "CompIsActive", "CompIsDeleted"],
            description="Legal organizational entities and companies.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="OrgDepartmentMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["DeptID"],
            important_columns=[
                "DeptID",
                "CompID",
                "DeptName",
                "MainDeptID",
                "DeptHeadEmpID",
                "DeptIsActive",
            ],
            description="Organizational departments and cost centers.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="OrgDesignationMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["DesigID"],
            important_columns=[
                "DesigID",
                "CompID",
                "DeptID",
                "DesigName",
                "DesigType",
                "DesigIsActive",
            ],
            description="Job titles and official designations.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="OrgLocationMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["LocID"],
            important_columns=["LocID", "LocName", "ShortName", "CompID", "LocIsActive"],
            description="Physical offices, manufacturing plants, and sites.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeGradeMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["EmpGradeID"],
            important_columns=[
                "EmpGradeID",
                "EmpGradeDesc",
                "NoticePeriodDays",
                "EmpGradeIsActive",
            ],
            description="Seniority and compensation grades.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeTypeMst",
            role=ModuleTableRole.LOOKUP,
            required=False,
            key_columns=["EmpTypeID"],
            important_columns=["EmpTypeID", "EmpTypeDesc", "EmpTypeIsActive"],
            description="Employment categories (e.g. Permanent, Contract, Intern).",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeFamilyDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["EmpFamilyDetID", "EmpID"],
            important_columns=[
                "EmpFamilyMemberName",
                "RelationID",
                "EmpFamilyIsEmergencyContact",
                "EmpFamilyMemberPhone",
            ],
            description="Family members, dependents, and emergency contacts.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeQualificationDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["EmpQualDetID", "EmpID"],
            important_columns=["DegreeID", "PassingYear", "GradePercentage", "InstituteName"],
            description="Academic qualifications and degrees.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeExperienceDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["EmpExpDetID", "EmpID"],
            important_columns=["CompanyName", "Designation", "FromDate", "ToDate", "LastDrawnCTC"],
            description="Prior employment experience history.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeAttendance",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["AttID", "AttEmpID"],
            important_columns=[
                "AttDate",
                "AttInTime",
                "AttOutTime",
                "AttStatus",
                "AttPresentHours",
            ],
            description="Daily biometric attendance punch logs and time tracking.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="PayLogEarnedSalary",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["EarnedSalID", "EarnedSalEmpID"],
            important_columns=["EarnedSalMonth", "EarnedSalGross", "EarnedSalNet", "EarnedSalDays"],
            description="Monthly processed salary records and compensation statements.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="PayMonthlyLeaveBalance",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["LeaveBalID", "EmpID"],
            important_columns=[
                "LeaveYear",
                "LeaveMonth",
                "OpeningBalance",
                "Earned",
                "Availed",
                "ClosingBalance",
            ],
            description="Monthly accrued, availed, and closing leave balances.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="EmployeeResignDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["EmpResignID", "EmpID"],
            important_columns=[
                "EmpResignApplyDate",
                "EmpLastDate",
                "StatusID",
                "HRStatusID",
                "EmpResignRemark",
            ],
            description="Resignation workflows, handover records, and approvals.",
        ),
    ],
    relationships=[
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeOfficialDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=True,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeReportingDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=True,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.SecurityUserMst",
            parent_key="EmpID",
            child_key="UserEmpID",
            relationship_type="ONE_TO_ONE",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeFamilyDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeQualificationDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeExperienceDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeAttendance",
            parent_key="EmpID",
            child_key="AttEmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.PayLogEarnedSalary",
            parent_key="EmpID",
            child_key="EarnedSalEmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.PayMonthlyLeaveBalance",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.EmployeeMst",
            child_table="dbo.EmployeeResignDet",
            parent_key="EmpID",
            child_key="EmpID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
    ],
    enabled=True,
    tags=["core", "master-data", "employee", "workforce", "hr", "payroll"],
)
