from app.modules.models import (
    ModuleDefinition,
    ModuleRelationshipDefinition,
    ModuleTableDefinition,
    ModuleTableRole,
)

PersonModuleDefinition = ModuleDefinition(
    code="PERSON",
    name="Person & Contact",
    description="Domain analysis for master person records, contact channels, physical addresses, company affiliations, person-to-person linkages, documents, custom fields, and instant messaging.",
    root_schema="dbo",
    root_table="DLPersonMst",
    root_key="PersonID",
    tables=[
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonMst",
            role=ModuleTableRole.ROOT,
            required=True,
            key_columns=["PersonID"],
            important_columns=[
                "PersonFirstName",
                "PersonLastName",
                "PersonIsActive",
                "PersonIsDeleted",
                "PersonIsTemp",
                "PersonIsBlackList",
                "PersonEntDt",
            ],
            description="Core master entity for individuals.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonAddressDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonAddID", "PersonID"],
            important_columns=[
                "Street",
                "CityName",
                "StateName",
                "PostalCode",
                "CountryID",
                "PersonAddIsActive",
                "Latitude",
                "Longitude",
                "GoogleFormattedAddress",
            ],
            description="Postal and physical address details.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonPhoneEmailURLDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonPhoneID", "PersionID"],
            important_columns=[
                "LabelTypeID",
                "TypeValue",
                "PersonPhoneIsActive",
                "IsVerified",
                "IsPrimary",
            ],
            description="Communication channels (phone numbers, email addresses, websites).",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonCompanyLinkDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonLinkID", "PersonID"],
            important_columns=["DLCompID", "CompPersonRoleID", "IsPrimary"],
            description="Affiliation and role links between persons and companies.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonRelationDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonRelationID", "PersonID"],
            important_columns=["RelatedPersonID", "RelationShipTypeID"],
            description="Inter-personal linkages and familial/professional relationships.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonDocumentDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonDocID", "PersonID"],
            important_columns=["PersonDocDesc", "PersonDocExtention", "PersonDocIsReadOnly"],
            description="Uploaded person attachments and documents.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonExtraFieldValueDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonExtraFieldValueID", "PersonID"],
            important_columns=["ExtraFieldID", "PersonExtraFieldValue", "PersonExtraFieldIsActive"],
            description="Custom dynamic fields and attribute values.",
        ),
        ModuleTableDefinition(
            schema="dbo",
            table="DLPersonIMDet",
            role=ModuleTableRole.DETAIL,
            required=False,
            key_columns=["PersonIMID", "PersionID"],
            important_columns=["LabelTypeIMID", "TypeValue"],
            description="Instant messaging handles and screen names.",
        ),
    ],
    relationships=[
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonAddressDet",
            parent_key="PersonID",
            child_key="PersonID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonPhoneEmailURLDet",
            parent_key="PersonID",
            child_key="PersionID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonCompanyLinkDet",
            parent_key="PersonID",
            child_key="PersonID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonRelationDet",
            parent_key="PersonID",
            child_key="PersonID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonDocumentDet",
            parent_key="PersonID",
            child_key="PersonID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonExtraFieldValueDet",
            parent_key="PersonID",
            child_key="PersonID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
        ModuleRelationshipDefinition(
            parent_table="dbo.DLPersonMst",
            child_table="dbo.DLPersonIMDet",
            parent_key="PersonID",
            child_key="PersionID",
            relationship_type="ONE_TO_MANY",
            required=False,
        ),
    ],
    enabled=True,
    tags=["core", "master-data", "person", "crm"],
)
